FROM apache/hadoop:3.4.1


USER root
RUN sed -i 's/mirror.centos.org/vault.centos.org/g' /etc/yum.repos.d/*.repo && \
    sed -i 's/#baseurl/baseurl/g' /etc/yum.repos.d/*.repo && \
    sed -i 's/mirrorlist=http/#mirrorlist=http/g' /etc/yum.repos.d/*.repo

# Sau khi sửa chữa liên kết, tiến hành cài đặt Python
RUN yum update -y && \
    yum install -y openssh-server openssh-clients python3 python3-pip && \
    mkdir -p /var/run/sshd && \
    ssh-keygen -A && \
    # Vô hiệu hóa kiểm tra host key nghiêm ngặt cho SSH bên trong cluster
    echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config && \
    yum clean all

# BƯỚC 3: Tạo key SSH cho Hadoop (để các dịch vụ tự giao tiếp)
RUN ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa && \
    cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

RUN pip3 install mrjob --no-cache-dir
RUN pip3 install cassandra-driver --no-cache-dir
RUN pip3 install kafka-python --no-cache-dir
RUN pip3 install hdfs --no-cache-dir
