{
 "title": "Retailrocket",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Real Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "view",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columnId": "event",
     "columnTime": "time_stamp",
     "columnValue": "count",
     "keyspace": "event_data_view",
     "table": "real_time_view",
     "valueId": "view"
    }
   ]
  },
  {
   "title": "addtocart",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columnId": "event",
     "columnTime": "time_stamp",
     "columnValue": "count",
     "keyspace": "event_data_view",
     "table": "real_time_view",
     "valueId": "addtocart"
    }
   ]
  },
  {
   "title": "transaction",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columnId": "event",
     "columnTime": "time_stamp",
     "columnValue": "count",
     "keyspace": "event_data_view",
     "table": "real_time_view",
     "valueId": "transaction"
    }
   ]
  },
  {
   "title": "Số lượt xem, thêm giỏ hàng, mua trong vòng 20s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 6 },
   "targets": [
    {
     "keyspace": "event_data_view",
     "table": "real_time_view",
     "target": "SELECT window_start, n_view\nFROM event_data_view.real_time_event_rate;"
    },
    {
     "target": "SELECT window_start, addtocart\nFROM event_data_view.real_time_event_rate;"
    },
    {
     "target": "SELECT window_start, transaction\nFROM event_data_view.real_time_event_rate;"
    }
   ]
  },
  { "title": "Batch View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Top 10 sản phẩm được xem nhiều nhất",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "SELECT  rank, itemid, total_count\nFROM event_data_view.top10_items\nWHERE event = 'view';"
    }
   ]
  },
  {
   "title": "Top 10 sản phẩm được thêm vào giỏ hàng nhiều nhất",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 16 },
   "targets": [
    {
     "target": "SELECT  rank, itemid, total_count\nFROM event_data_view.top10_items\nWHERE event = 'addtocart';"
    }
   ]
  },
  {
   "title": "Top 10 sản phẩm được mua nhiều nhất",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 16 },
   "targets": [
    {
     "target": "SELECT  rank, itemid, total_count\nFROM event_data_view.top10_items\nWHERE event = 'transaction';"
    }
   ]
  },
  {
   "title": "Tổng số lượt xem, thêm giỏ hàng và mua",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT \n     view_to_cart_rate AS \"Tỷ lệ view→cart (%)\",\n    cart_to_transaction_rate AS \"Tỷ lệ cart→transaction (%)\",\n    view_to_transaction_rate AS \"Tỷ lệ view→transaction (%)\"\nFROM event_data_view.conversion_rate;"
    }
   ]
  },
  {
   "title": "Tổng số lượt xem, thêm giỏ hàng và mua",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT \n    n_view AS \"Số lượt xem\",\n    addtocart AS \"Số lượt thêm giỏ\",\n    transaction AS \"Số lượt mua\"\nFROM event_data_view.conversion_rate;"
    }
   ]
  },
  {
   "title": "Top 10 sản phẩm có tỉ lệ hủy giỏ hàng cao nhất",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 32 },
   "targets": [
    {
     "target": "SELECT \n    itemid AS \"Mã sản phẩm\",\n    addtocart AS \"Số lần thêm vào giỏ\",\n    transaction AS \"Số lần mua hàng\",\n    abandoned_count AS \"Số lần bỏ giỏ\",\n    abandon_rate AS \"Tỷ lệ bỏ giỏ\"\nFROM event_data_view.top_abandoned_items\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Danh sách các sản phẩm thường chọn kèm với nhau",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 42 },
   "targets": [
    {
     "target": "SELECT items AS \"Sản phẩm\", freq AS \"Số lần xuất hiện\"\nFROM event_data_view.frequent_itemsets\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Luật kết hợp",
   "type": "table",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 50 },
   "targets": [
    {
     "target": "SELECT \n    antecedent AS \"Sản phẩm ban đầu\",\n    consequent AS \"Sản phẩm đi kèm\",\n    confidence AS \"Độ tin cậy\",\n    lift AS \"Độ nâng\"\nFROM event_data_view.association_rules\nLIMIT 10;"
    }
   ]
  }
 ]
}